'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster, toast } from "sonner";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Mentor Hub",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {children}
        </div>
          <Toaster richColors position="top-right"/>  
      </body>
    </html>
  );
}
